language: php
php:
  - '7.1'

addons:
  code_climate:
    repo_token: 83dfa6c83608f32a87187472eee92e59af04c60292c428f76b5fff97c20a8f8f

install:
  - composer self-update
  - make install

script: make lint test